# Generated by Django 3.0.5 on 2020-06-20 15:45

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
